<a href="https://colab.research.google.com/github/youssy99/Pytorch-Learning/blob/main/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

LISTS

In [5]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.1977696 , 0.27131634, 0.22590557, 0.5372717 ],
       [0.96429285, 0.23128648, 0.96963307, 0.23508082],
       [0.54530001, 0.21349766, 0.09970639, 0.36340548]])

Tensors

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1978, 0.2713, 0.2259, 0.5373],
        [0.9643, 0.2313, 0.9696, 0.2351],
        [0.5453, 0.2135, 0.0997, 0.3634]], dtype=torch.float64)